RealEstate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve as mediaserve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('catalog/', include('catalog.urls')),
    path('sale/', include('sale.urls')),
    path('feedback/', include('feedback.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]

about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('', views.index, name='about'),
]

catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.apartments_list, name='apartments_list'),
    path('<int:pk>/', views.single_apartment, name='single_apartment'),
    path('<str:category_id>/', views.apartments_list, name='category'),

]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

from catalog.models import Apartments


def index(request):
    last_apartments = Apartments.objects.filter(show=True).order_by('-date')[:6]

    data = {'apartments': last_apartments}

    return render(request, 'home.html', context=data)

home/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
    <!-- Header Start -->
    <div class="container-fluid header bg-white p-0">
        <div class="row g-0 align-items-center flex-column-reverse flex-md-row">
            <div class="col-md-6 p-5 mt-lg-5">
                <h1 class="display-5 animated fadeIn mb-4">Найдите <span
                        class="text-primary">идеальную недвижимость</span></h1>
                <p class="animated fadeIn mb-4 pb-2">Выбирайте среди проверенной базы объектов. Сделку под ключ для вас
                    организуют наши специалисты по недвижимость</p>
                <a href="{% url 'catalog:apartments_list' %}" class="btn btn-primary py-3 px-5 me-3 animated fadeIn">Начать</a>
            </div>
            <div class="col-md-6 animated fadeIn">
                <div class="owl-carousel header-carousel">
                    <div class="owl-carousel-item">
                        <img class="img-fluid" src="{% static 'img/IMG-20240405-WA0207.jpg' %}" alt="">
                    </div>
                    <div class="owl-carousel-item">
                        <img class="img-fluid" src="{% static 'img/IMG-20240405-WA0219.jpg' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

{% endblock %}

{% block content %}

    {#    {% include 'search.html' %}#}

    <!-- Category Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">
                <h1 class="mb-3">Наши услуги</h1>
                <p>Ищете надежные риэлторские агентства? Мы предоставляем комплексное
                    риэлторское, брокерское, юридическое сопровождение.</p>
            </div>
            <div class="row g-4 align-items-center justify-content-center">
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                    <a class="cat-item d-block bg-light text-center rounded p-3" href="#">
                        <div class="rounded p-4">
                            <div class="icon mb-3">
                                <img class="img-fluid" src="{% static 'img/icon-apartment.png' %}" alt="Icon">
                            </div>
                            <h6>Продажа недвижимость от застройщиков</h6>
                        </div>
                    </a>
                </div>
                {#                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">#}
                {#                    <a class="cat-item d-block bg-light text-center rounded p-3" href="">#}
                {#                        <div class="rounded p-4">#}
                {#                            <div class="icon mb-3">#}
                {#                                <img class="img-fluid" src="{% static 'img/icon-villa.png' %}" alt="Icon">#}
                {#                            </div>#}
                {#                            <h6>Оформление договоров купли-продажи</h6>#}
                {#                        </div>#}
                {#                    </a>#}
                {#                </div>#}
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
                    <a class="cat-item d-block bg-light text-center rounded p-3" href="#">
                        <div class="rounded p-4">
                            <div class="icon mb-3">
                                <img class="img-fluid" src="{% static 'img/icon-house.png' %}" alt="Icon">
                            </div>
                            <h6>Проверка объектов недвижимости</h6>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
                    <a class="cat-item d-block bg-light text-center rounded p-3" href="#">
                        <div class="rounded p-4">
                            <div class="icon mb-3">
                                <img class="img-fluid" src="{% static 'img/icon-housing.png' %}" alt="Icon">
                            </div>
                            <h6>Консультация по рынку недвижимости в регионе. Оценка динамики цен и спроса</h6>
                        </div>
                    </a>
                </div>
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                    <a class="cat-item d-block bg-light text-center rounded p-3" href="#">
                        <div class="rounded p-4">
                            <div class="icon mb-3">
                                <img class="img-fluid" src="{% static 'img/icon-building.png' %}" alt="Icon">
                            </div>
                            <h6>Подбор вариантов недвижимости с учетом всех
                                пожеланий и потребностей</h6>
                        </div>
                    </a>
                </div>
                {#                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">#}
                {#                    <a class="cat-item d-block bg-light text-center rounded p-3" href="">#}
                {#                        <div class="rounded p-4">#}
                {#                            <div class="icon mb-3">#}
                {#                                <img class="img-fluid" src="{% static 'img/icon-condominium.png' %}" alt="Icon">#}
                {#                            </div>#}
                {#                            <h6>Помощь в подготовке и оформлении документов для сделки</h6>#}
                {#                        </div>#}
                {#                    </a>#}
                {#                </div>#}
                <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
                    <a class="cat-item d-block bg-light text-center rounded p-3" href="#">
                        <div class="rounded p-4">
                            <div class="icon mb-3">
                                <img class="img-fluid" src="{% static 'img/icon-luxury.png' %}" alt="Icon">
                            </div>
                            <h6>
                                Полное юридическое сопровождение сделки
                            </h6>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Category End -->

    <!-- About Start -->
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5 align-items-center">
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                    <div class="about-img position-relative overflow-hidden p-5 pe-0">
                        <img class="w-100" src="{% static 'img/IMG-20240405-WA0208.jpg' %}" alt="">
                    </div>
                </div>
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                    <h1 class="mb-4">Место, где можно найти <span class="text-primary"> Идеальную недвижимость</span>
                    </h1>
                    <p class="mb-4">Мы работаем в сфере недвижимости и строим компанию нового типа – сочетаем инновации,
                        ответственность и человеческое отношение к каждому клиенту. Компания инвестирует в обучение,
                        автоматизацию процессов, исследования и качество услуг.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Доступ к огромной базе жилья</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Оформление всех этапов сделок</p>
                    <p><i class="fa fa-check text-primary me-3"></i>Экономия деньг за счет эксклюзивных скидок от
                        надежных партнеров</p>
                    <a class="btn btn-primary py-3 px-5 mt-3" href="{% url 'about:about' %}">Узнать больше</a>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->
    {% if apartments %}
        <div class="container px-4 pt-5">
            <div class="col-lg-6">
                <div class="text-start mx-auto mb-5 wow slideInLeft" data-wow-delay="0.1s">
                    <h1 class="mb-3">Каталог квартир</h1>
                    <p>Наша компания защищает интересы клиента в случае юридических проблем по сделке</p>
                </div>
            </div>
        </div>


        {% include 'apartment_catalog_base.html' with apartments=apartments %}

        <div class="col-12 text-center">
            <a class="btn btn-primary py-3 px-5" href="{% url 'catalog:apartments_list' %}">Показать больше</a>
        </div>
    {% endif %}



    {% include 'testimonial.html' %}



    {% include 'contact_base.html' %}


{% endblock %}