RealEstate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve as mediaserve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('catalog/', include('catalog.urls')),
    path('sale/', include('sale.urls')),
    path('feedback/', include('feedback.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]

catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.apartments_list, name='apartments_list'),
    path('<int:pk>/', views.single_apartment, name='single_apartment'),
    path('<str:category_id>/', views.apartments_list, name='category'),

]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

catalog/models.py
from datetime import datetime

from django.db import models

STATUS_CHOICES = (
    ('for_sale', 'на продаже'),
    ('sales', 'продано'),
)

APARTMENT_TYPE = (
    ('secondary', 'вторичная'),
    ('new_buildings', 'новостройки'),
)


class Apartments(models.Model):
    title = models.CharField('Название', max_length=500)
    description = models.TextField('Описание')
    status = models.CharField('Статус', choices=STATUS_CHOICES, max_length=50, default='for_sale')
    type = models.CharField('Тип недвижимости', choices=APARTMENT_TYPE, max_length=70, default='new_buildings')
    show = models.BooleanField('Показывать на сайте?', default=False)
    price = models.IntegerField('Цена', default=1)
    floor = models.IntegerField('Этаж', default=1)
    bedrooms = models.IntegerField('Колличество комнат', default=1)
    sqft_living = models.FloatField('Сколько квадратных метров', default=1)
    address = models.CharField('Адрес', max_length=500, default=None, blank=True, null=True)
    wall_material = models.CharField('Материал стен', max_length=500, default=None, blank=True, null=True)
    the_developer = models.CharField('Застройщик', max_length=500, default=None, blank=True, null=True)
    lat = models.FloatField('Широта', blank=True, null=True)
    lon = models.FloatField('Долгота', blank=True, null=True)
    plan = models.ImageField('Планировка', upload_to='media/', blank=True)
    external = models.BooleanField('Создано внешними клиентами?', default=False)
    contacts = models.TextField('Контакты для связи', blank=True, null=True)
    date = models.DateTimeField('Дата публикации', default=datetime.now())

    def __str__(self):
        return self.title

    def first_image(self):
        return self.images.first()

    class Meta:
        verbose_name = 'Квартиру'
        verbose_name_plural = 'Квартиры'


class Images(models.Model):
    apartment = models.ForeignKey(Apartments, default=None, on_delete=models.CASCADE, related_name="images", )
    image = models.ImageField('Изображение', upload_to='media/', blank=True)

    def __str__(self):
        return self.apartment.title

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображение'

catalog/views.py
from django.shortcuts import render
from django.core.paginator import Paginator

from .models import Apartments


def apartments_list(request, category_id='all'):
    all_category = ['for_sale', 'sales']

    if category_id in all_category:
        all_apartments = Apartments.objects.filter(status=category_id, show=True).order_by('-date')
    else:
        all_apartments = Apartments.objects.filter(show=True).order_by('-date')

    paginator = Paginator(all_apartments, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    data = {
        'page_obj': page_obj,
        'category': category_id,
    }

    return render(request, 'apartments_list.html', context=data)


def single_apartment(request, pk=None):
    apartment = Apartments.objects.get(id=pk, show=True)

    data = {
        'apartment': apartment,
    }

    return render(request, 'single_apartment.html', context=data)

catalog/templates/apartments_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {#    {% include 'search.html' %}#}
    <div class="container-fluid header bg-white mt-5">
        <div class="row g-0 align-items-center flex-column-reverse flex-md-row">
            <div class="col-md-6 p-5 mt-lg-5">
                <h1 class="display-5 animated fadeIn mb-4">Каталог недвижимости</h1>
                <p class="animated fadeIn mb-4 pb-2">Наша компания защищает интересы клиента в случае юридических
                    проблем по сделке</p>
            </div>
            <div class="col-md-6 animated fadeIn">
                <ul class="nav nav-pills d-inline-flex mb-5">
                    <li class="nav-item me-2">
                        <a class="btn btn-outline-primary {% if category == 'all' %} active {% endif %}"
                           href="{% url 'catalog:category' 'all' %}">Все</a>
                    </li>
                    <li class="nav-item me-2">
                        <a class="btn btn-outline-primary {% if category == 'for_sale' %} active {% endif %}"
                           href="{% url 'catalog:category' 'for_sale' %}">На продажу</a>
                    </li>
                    <li class="nav-item me-0">
                        <a class="btn btn-outline-primary {% if category == 'sales' %} active {% endif %}"
                           href="{% url 'catalog:category' 'sales' %}">Продано</a>
                    </li>
                </ul>
            </div>
        </div>

    </div>

    {% include 'apartment_catalog_base.html' with apartments=page_obj %}
    {% include 'contact_base.html' %}
{% endblock %}

catalog/templates/single_apartment.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div class="container px-3 mt-5">
        <div class="owl-carousel testimonial-carousel wow fadeInUp" data-wow-delay="0.1s">
            {% for image in apartment.images.all %}
                <div class="testimonial-item rounded p-3">
                    <img class="img-fluid" src="{{ image.image.url }}" alt="">
                </div>
            {% endfor %}
        </div>
    </div>


    <div class="container-fluid wow fadeIn" data-wow-delay="0.1s">
        <h1 class="display-6 mt-5 text-center">{{ apartment.title }}</h1>
        <h5 class="display-6 ps-5 text-primary mb-3">
            <i class="fa fa-ruble-sign text-primary me-2"></i>
            {{ apartment.price }}
        </h5>

        <div class="row g-0 align-items-center flex-column-reverse flex-md-row">
            <div class="col-md-6 p-5">
                <ul>
                    <li class="d-flex justify-content-between">
                        <strong>Адрес:</strong>
                        <span>{{ apartment.address }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                        <strong>Статус:</strong>
                        <span>{{ apartment.get_status_display.capitalize }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                        <strong>Площать:</strong>
                        <span>{{ apartment.sqft_living }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                        <strong>Комнаты:</strong>
                        <span>{{ apartment.bedrooms }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                        <strong>Материал стен:</strong>
                        <span>{{ apartment.wall_material }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                        <strong>Застройщик:</strong>
                        <span>{{ apartment.the_developer }}</span>
                    </li>
                </ul>
            </div>
            <div class="col-md-6">
                {{ apartment.description }}
            </div>
        </div>
    </div>


    <div class="container-fluid wow fadeIn mb-5" data-wow-delay="0.1s">
        <div class="row g-0 flex-column-reverse flex-md-row">

            <div class="col-md-6 p-5">
                {% if apartment.plan.url is not None %}
                    <img class="img-fluid" src="{{ apartment.plan.url }}" alt="">
                {% endif %}
            </div>

            <div class="col-md-6 pt-5">
                {% if apartment.lat is not None and  apartment.lat is not None %}
                    <div id="map" style="height: 55vh"></div>
                {% endif %}
            </div>
        </div>
    </div>

    {% include 'contact_base.html' %}

    <script>

        var lon = parseFloat("{{apartment.lon}}".replace(",", "."));
        var lat = parseFloat("{{apartment.lat}}".replace(",", "."));

        var map = new L.map('map', {
            zoomAnimation: true,
            zoomControl: false
        }).setView([!isNaN(lat) ? lat : 43.4974784851074, !isNaN(lon) ? lon : 43.655876159668], 12);

        let layer = L.tileLayer(
            'http://tile2.maps.2gis.com/tiles?x={x}&y={y}&z={z}',
            {
                subdomains: ['01', '02', '03', '04'],
                attribution: '&copy; <a target="_blank" href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            }
        );

        if (!isNaN(lat) && !isNaN(lon)) {

            var myIcon = L.icon({
                iconUrl: "{% static 'img/marker-icon.png' %}",
                iconSize: [55, 55],
                iconAnchor: [22, 94],
            });

            L.marker([lat, lon], {icon: myIcon}).addTo(map);

        }


        map.addLayer(layer);

    </script>


{% endblock %}