RealEstate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve as mediaserve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('catalog/', include('catalog.urls')),
    path('sale/', include('sale.urls')),
    path('feedback/', include('feedback.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

sale/urls.py
from django.urls import path

from . import views

app_name = 'sale'

urlpatterns = [
    path('', views.how_sale, name='how_sale'),
    path('post', views.sale, name='post'),
]

sale/models.py
# from django.db import models
#
# from catalog.models import Apartments
#
#
# class ExternalApartments(Apartments):
#     contacts = models.TextField('Контакты для связи', blank=True)
#     external = models.BooleanField('Создано внешними клиентами?', default=False)
#
#     class Meta:
#         verbose_name = 'Квартиру'
#         verbose_name_plural = 'Квартиры'

sale/forms.py
from django import forms

from catalog.models import Apartments
from catalog.models import Images


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class ExternalApartmentsFormModel(forms.ModelForm):
    class Meta:
        model = Apartments
        fields = (
            'type', 'address', 'floor', 'bedrooms', 'sqft_living', 'wall_material', 'title', 'description', 'price',
            'contacts', 'plan')

        widgets = {
            'type': forms.RadioSelect(attrs={'class': 'form-check-input', 'required': True}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'floor': forms.NumberInput(attrs={'class': 'form-control', 'required': True}),
            'bedrooms': forms.NumberInput(attrs={'class': 'form-control', 'required': True}),
            'sqft_living': forms.NumberInput(attrs={'class': 'form-control', 'required': True}),
            'wall_material': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'title': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'required': True}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'required': True}),
            'contacts': forms.Textarea(
                attrs={'class': 'form-control', 'placeholder': 'номер телефона, почта, WhatsApp или Telegram',
                       'required': True}, ),

        }

    def save(self, commit=True):
        instance = super(ExternalApartmentsFormModel, self).save(commit=False)
        instance.external = True

        if commit:
            instance.save()

        return instance


class ExternalApartmentsImagesForm(forms.ModelForm):
    class Meta:
        model = Images
        fields = {'apartment', 'image'}
        widgets = {
            'image': MultipleFileInput()
        }

sale/views.py
from django.shortcuts import render
from django.http import JsonResponse

from .forms import ExternalApartmentsFormModel, ExternalApartmentsImagesForm
from catalog.models import Images
from telegram_bot.main_bot import send_message


def how_sale(request):
    return render(request, 'how_sale.html')


def sale(request):
    if request.method == 'POST':

        form = ExternalApartmentsFormModel(request.POST, request.FILES)

        if form.is_valid():
            instance = form.save(commit=True)

            try:
                for f in request.FILES.getlist('image'):
                    external = Images(
                        apartment=instance,
                        image=f
                    )
                    external.save()
            except Exception as e:
                pass

            message = "Добавлена новая квартира!"
            send_message(message=message)
            return JsonResponse("Успешно отправлено", status=200, safe=False)
        else:
            return JsonResponse(form.errors, status=400, safe=False)

    else:
        sale_form = ExternalApartmentsFormModel()
        images_form = ExternalApartmentsImagesForm()
        return render(request, 'sale.html', {'form': sale_form, 'images_form': images_form})

sale/templates/how_sale.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-xxl py-5">
        <div class="container">
            <div class="rounded p-3">
                <div class="bg-white rounded p-4" style="border: 1px dashed rgba(0, 185, 142, .3)">
                    <div class="row g-5 align-items-center">
                        <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                            <div class="mb-4">
                                <h1 class="mb-3">Поможем продать недвижимость быстро и выгодно</h1>
                                <p>Разместите объявление о продаже и покупатели увидят его на сайте</p>
                            </div>
                            <a href="{% url 'sale:post' %}" class="btn btn-primary py-3 px-4 me-2"><i class="fa fa-phone-alt me-2"></i>
                                Добавить объявление
                            </a>
                        </div>
                        <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                            <img class="img-fluid rounded w-100" src="{% static 'img/sale.png' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-xxl">
        <div class="container">

            <div class="rounded p-3">
                <div class="bg-white rounded p-4">
                    <h1 class="mb-3">Как это работает</h1>
                    <div class="row g-5 align-items-center">
                        <div class="col-lg-7 wow fadeIn" data-wow-delay="0.5s">
                            <div class="accordion accordion-flush" id="accordionFlushExample">
                                <div class="accordion-item bg-white">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed bg-white" type="button"
                                                data-bs-toggle="collapse"
                                                data-bs-target="#flush-collapseOne" aria-expanded="false"
                                                aria-controls="flush-collapseOne">
                                            1. Размещение объявления
                                        </button>
                                    </h2>
                                    <div id="flush-collapseOne" class="accordion-collapse collapse"
                                         data-bs-parent="#accordionFlushExample">
                                        <div class="accordion-body">
                                            <p>
                                                - Добавьте объявление о своей недвижимости, и через 2 часа
                                                покупатели увидят его на сайте. Или просто оставьте свой телефон и мы
                                                всё
                                                сделаем.
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item bg-white">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed bg-white" type="button"
                                                data-bs-toggle="collapse"
                                                data-bs-target="#flush-collapseTwo" aria-expanded="false"
                                                aria-controls="flush-collapseTwo">
                                            2. Подготовка к продаже
                                        </button>
                                    </h2>
                                    <div id="flush-collapseTwo" class="accordion-collapse collapse"
                                         data-bs-parent="#accordionFlushExample">
                                        <div class="accordion-body">
                                            <p>- Добавим фотографии, планировку и сделаем привлекательное описание
                                                вашего
                                                предложения.</p>
                                            <p>- Подписание агентского договора в офисе или онлайн.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item bg-white">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed bg-white" type="button"
                                                data-bs-toggle="collapse"
                                                data-bs-target="#flush-collapseThree" aria-expanded="false"
                                                aria-controls="flush-collapseThree">
                                            3. Поиск покупателей
                                        </button>
                                    </h2>
                                    <div id="flush-collapseThree" class="accordion-collapse collapse"
                                         data-bs-parent="#accordionFlushExample">
                                        <div class="accordion-body">
                                            <p>- Мы разместим ваше объявление на популярных площадках города по поиску
                                                недвижимости.</p>
                                            <p>- Специалист по недвижимости проведет личные или онлайн показы вашего
                                                объекта для
                                                заинтересованных покупателей.</p>

                                        </div>
                                    </div>
                                </div>
                                <div class="accordion-item bg-white">
                                    <h2 class="accordion-header">
                                        <button class="accordion-button collapsed bg-white" type="button"
                                                data-bs-toggle="collapse"
                                                data-bs-target="#flush-collapseFore" aria-expanded="false"
                                                aria-controls="flush-collapseThree">
                                            4. Заключение сделки
                                        </button>
                                    </h2>
                                    <div id="flush-collapseFore" class="accordion-collapse collapse"
                                         data-bs-parent="#accordionFlushExample">
                                        <div class="accordion-body">
                                            <p>- Берём на себя весь процесс подготовки документов и проведения
                                                сделки.</p>
                                            <p>- Организовываем и сопровождаем процесс передачи задатка, можно
                                                онлайн.</p>
                                            <p>- Оплачиваете услуги компании.</p>
                                            <p>- Проводим сделку , регистрируем право собственности в МФЦ или через
                                                электронную
                                                регистрацию.</p>
                                            <p>- Передаете ключи.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-5 wow fadeIn" data-wow-delay="0.1s">
                            <img class="img-fluid rounded w-100" src="{% static 'img/deal.png' %}" alt="">
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>


{% endblock %}

sale/templates/sale.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-xxl py-5">
        <div class="container">
            <div class="rounded p-3">
                <div class="bg-white rounded p-4" style="border: 1px dashed rgba(0, 185, 142, .3)">
                    <div class="row g-5 align-items-center">
                        <div class="col-lg-8 wow fadeIn" data-wow-delay="0.5s">
                            <div class="mb-4">
                                <h1 class="mb-3">Продайте недвижимость быстро и без хлопот</h1>
                                <p>Разместите объявление о продаже или обратитесь за помощью к нашим специалистам</p>
                            </div>
                            <button class="btn btn-primary py-3 px-4 me-2" data-bs-toggle="modal"
                                    data-bs-target="#feedback-modal">Мне нужна помощь
                            </button>
                        </div>
                        <div class="col-lg-4 wow fadeIn" data-wow-delay="0.1s">
                            <img class="img-fluid rounded w-100" src="{% static 'img/search.png' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-xxl">
        <div class="container">
            <div class="rounded p-3">
                <div class="bg-white rounded p-4" style="border: 1px dashed rgba(0, 185, 142, .3)">
                    <h2>Добавить объявление</h2>
                    <form id="postForm" method="post" class="mt-5" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="my-4">
                            <label class="mb-2 fw-bold">{{ form.type.label }}</label>
                            <div>
                                {% for radio in form.type %}
                                    <div class="form-check">
                                        {{ radio }}
                                        <label class="form-check-label"
                                               for="{{ radio.id_for_label }}">{{ radio.choice_label }}</label>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="row gy-3">
                            <div class="col-md-4">
                                <label for="{{ form.auto_id }}"
                                       class="form-label fw-bold">{{ form.address.label_tag }}</label>
                                {{ form.address }}
                            </div>
                            <div class="col-md-4">
                                <label for="{{ form.auto_id }}"
                                       class="form-label fw-bold">{{ form.floor.label_tag }}</label>
                                {{ form.floor }}
                            </div>
                        </div>

                        <div class="my-4">
                            <div class="col-md-4">
                                <label for="{{ form.auto_id }}"
                                       class="form-label fw-bold">{{ form.bedrooms.label_tag }}</label>
                                {{ form.bedrooms }}
                            </div>
                        </div>

                        <div class="my-4">
                            <div class="row gy-3">
                                <div class="col-md-4">
                                    <label for="{{ form.auto_id }}"
                                           class="form-label fw-bold">{{ form.sqft_living.label_tag }}</label>
                                    <div class="input-group has-validation">
                                        {{ form.sqft_living }}
                                        <span class="input-group-text">
                                                            <span class="eWjiV">м<sup>2</sup></span>
                                                        </span>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <label for="{{ form.auto_id }}"
                                           class="form-label fw-bold">{{ form.wall_material.label_tag }}</label>
                                    {{ form.wall_material }}
                                </div>
                            </div>
                        </div>

                        <div class="my-4">
                            <div class="row gy-3">
                                <div class="col-md-4">
                                    <div class="row pb-2">
                                        <label for="{{ form.auto_id }}"
                                               class="form-label fw-bold pb-0 mb-0">{{ form.plan.label_tag }} </label>
                                        <small>только (jpeg/png)</small>
                                    </div>

                                    {{ form.plan }}
                                </div>
                                <div class="col-md-4">
                                    <div class="row pb-2">
                                        <label for="{{ form.auto_id }}"
                                               class="form-label fw-bold pb-0 mb-0">{{ images_form.image.label_tag }}
                                        </label>
                                        <small>только (jpeg/png)</small>
                                    </div>

                                    {{ images_form.image }}
                                </div>
                            </div>
                        </div>

                        <div class="my-4">
                            <div class="col-md-4">
                                <label for="{{ form.auto_id }}"
                                       class="form-label fw-bold">{{ form.title.label_tag }}</label>
                                {{ form.title }}
                            </div>
                        </div>

                        <div class="my-4">
                            <div class="col-md-8">
                                <label for="{{ form.auto_id }}"
                                       class="form-label fw-bold">{{ form.description.label_tag }}</label>
                                {{ form.description }}
                            </div>
                        </div>

                        <div class="my-4">
                            <div class="col-md-4">
                                <label for="{{ form.auto_id }}"
                                       class="form-label fw-bold">{{ form.price.label_tag }}</label>
                                <div class="input-group has-validation">
                                    {{ form.price }}
                                    <span class="input-group-text">
                                                            <span class="eWjiV">₽</span>
                                                        </span>
                                </div>
                            </div>
                        </div>

                        <div class="my-4">
                            <div class="col-md-4">
                                <label for="{{ form.auto_id }}"
                                       class="form-label fw-bold">{{ form.contacts.label_tag }}</label>
                                {{ form.contacts }}
                            </div>
                        </div>

                        <div class="my-4">
                            <input type="submit" value="Опубликовать" class="btn btn-primary py-3 px-4 me-2">
                        </div>
                        {{ form.errors }}
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="success-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="col">
                        <div class="form h-100 contact-wrap p-5">
                            <h3 class="text-center mb-5">Объявление успаешно добавлено! Через 2 часа покупатели увидят
                                его на
                                сайте!</h3>
                            <div class="mb-5">
                                <div class="row justify-content-center">
                                    <div class="col-md-5 form-group text-center">
                                        <button type="button" class="btn btn-success btn-block" data-bs-dismiss="modal">
                                            Закрыть
                                        </button>
                                        <span class="submitting"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="error-modal" tabindex="-1" aria-labelledby="exampleModalLabel1" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="col">
                        <div class="form h-100 contact-wrap p-5">
                            <h3 class="text-center mb-5">Ошибка при добавлении объявления! Проверьте введенные
                                данные</h3>
                            <div class="mb-5">
                                <div class="row justify-content-center">
                                    <div class="col-md-5 form-group text-center">
                                        <button type="button" class="btn btn-success btn-block" data-bs-dismiss="modal">
                                            Закрыть
                                        </button>
                                        <span class="submitting"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>

        $(function () {
            $('#postForm').on('submit', function (event) {
                event.preventDefault()
                var formData = new FormData(this);
                $.ajax({
                    url: '{% url "sale:post" %}',
                    type: 'POST',
                    data: formData,
                    success: function (data, textStatus, xhr) {
                        if (xhr.status === 200) {
                            $('#success-modal').modal('show');
                        } else {
                            $('#error-modal').modal('show')
                        }


                    },
                    error: function (response) {
                        $('#error-modal').modal('show')
                        console.log(response)
                    },
                    cache: false,
                    contentType: false,
                    processData: false
                });
                $('#postForm')[0].reset();
            });
        });
    </script>

{% endblock %}