RealEstate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve as mediaserve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
    path('catalog/', include('catalog.urls')),
    path('sale/', include('sale.urls')),
    path('feedback/', include('feedback.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

else:
    urlpatterns += [
        re_path(f'^{settings.MEDIA_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.MEDIA_ROOT}),
        re_path(f'^{settings.STATIC_URL.lstrip("/")}(?P<path>.*)$',
                mediaserve, {'document_root': settings.STATIC_ROOT}),
    ]

catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.apartments_list, name='apartments_list'),
    path('<int:pk>/', views.single_apartment, name='single_apartment'),
    path('<str:category_id>/', views.apartments_list, name='category'),

]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

catalog/models.py
from datetime import datetime

from django.db import models

STATUS_CHOICES = (
    ('for_sale', 'на продаже'),
    ('sales', 'продано'),
)

APARTMENT_TYPE = (
    ('secondary', 'вторичная'),
    ('new_buildings', 'новостройки'),
)


class Apartments(models.Model):
    title = models.CharField('Название', max_length=500)
    description = models.TextField('Описание')
    status = models.CharField('Статус', choices=STATUS_CHOICES, max_length=50, default='for_sale')
    type = models.CharField('Тип недвижимости', choices=APARTMENT_TYPE, max_length=70, default='new_buildings')
    show = models.BooleanField('Показывать на сайте?', default=False)
    price = models.IntegerField('Цена', default=1)
    floor = models.IntegerField('Этаж', default=1)
    bedrooms = models.IntegerField('Колличество комнат', default=1)
    sqft_living = models.FloatField('Сколько квадратных метров', default=1)
    address = models.CharField('Адрес', max_length=500, default=None, blank=True, null=True)
    wall_material = models.CharField('Материал стен', max_length=500, default=None, blank=True, null=True)
    the_developer = models.CharField('Застройщик', max_length=500, default=None, blank=True, null=True)
    lat = models.FloatField('Широта', blank=True, null=True)
    lon = models.FloatField('Долгота', blank=True, null=True)
    plan = models.ImageField('Планировка', upload_to='media/', blank=True)
    external = models.BooleanField('Создано внешними клиентами?', default=False)
    contacts = models.TextField('Контакты для связи', blank=True, null=True)
    date = models.DateTimeField('Дата публикации', default=datetime.now())

    def __str__(self):
        return self.title

    def first_image(self):
        return self.images.first()

    class Meta:
        verbose_name = 'Квартиру'
        verbose_name_plural = 'Квартиры'


class Images(models.Model):
    apartment = models.ForeignKey(Apartments, default=None, on_delete=models.CASCADE, related_name="images", )
    image = models.ImageField('Изображение', upload_to='media/', blank=True)

    def __str__(self):
        return self.apartment.title

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображение'

templates/apartment_catalog_base.html
{% load static %}


<div class="container-fluid">
    <div class="row g-0 align-items-center flex-column-reverse flex-md-row">
        <div class="col p-5">
            <div class="tab-content">
                <div class="tab-pane fade show p-0 active">
                    <div class="row g-0 align-items-center flex-column-reverse flex-md-row">
                        {% for apart in apartments %}

                            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                                <div class="property-item rounded overflow-hidden">
                                    <div class="position-relative overflow-hidden">
                                        <a href="{% url 'catalog:single_apartment' apart.id %}">
                                            <img class="img-fluid" src="{{ apart.first_image.image.url }}" alt="">
                                        </a>
                                        <div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">
                                            {{ apart.get_status_display }}
                                        </div>
                                        <div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">
                                            {{ apart.get_type_display.capitalize }}
                                        </div>
                                    </div>
                                    <div class="p-4 pb-0">
                                        <h5 class="text-primary mb-3">
                                            <i class="fa fa-ruble-sign text-primary me-2"></i>
                                            {{ apart.price }}
                                        </h5>
                                        <a class="d-block h5 mb-2"
                                           href="{% url 'catalog:single_apartment' apart.id %}">{{ apart.title }}</a>
                                        <p>
                                            <i class="fa fa-map-marker-alt text-primary me-2"></i>
                                            {{ apart.address }}
                                        </p>
                                    </div>
                                    <div class="d-flex border-top">
                                        <small class="flex-fill text-center border-end py-2"><i
                                                class="fa fa-ruler-combined text-primary me-2"></i>
                                            Площадь: {{ apart.sqft_living }} м2
                                        </small>
                                        <small class="flex-fill text-center border-end py-2"><i
                                                class="fa fa-bed text-primary me-2"></i>
                                            Комнаты: {{ apart.bedrooms }}
                                        </small>
                                    </div>
                                </div>
                            </div>

                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Property List Start -->
{#<div class="container-fluid py-5">#}
{#    <div class="tab-content">#}
{#        <div class="tab-pane fade show p-0 active">#}
{#            <div class="row g-0 align-items-center flex-column-reverse flex-md-row">#}
{#                {% for apart in apartments %}#}
{##}
{#                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">#}
{#                        <div class="property-item rounded overflow-hidden">#}
{#                            <div class="position-relative overflow-hidden">#}
{#                                <a href="{% url 'catalog:single_apartment' apart.id %}">#}
{#                                    <img class="img-fluid" src="{{ apart.first_image.image.url }}" alt="">#}
{#                                </a>#}
{#                                <div class="bg-primary rounded text-white position-absolute start-0 top-0 m-4 py-1 px-3">#}
{#                                    {{ apart.get_status_display }}#}
{#                                </div>#}
{#                                <div class="bg-white rounded-top text-primary position-absolute start-0 bottom-0 mx-4 pt-1 px-3">#}
{#                                    {{ apart.get_type_display.capitalize }}#}
{#                                </div>#}
{#                            </div>#}
{#                            <div class="p-4 pb-0">#}
{#                                <h5 class="text-primary mb-3">#}
{#                                    <i class="fa fa-ruble-sign text-primary me-2"></i>#}
{#                                    {{ apart.price }}#}
{#                                </h5>#}
{#                                <a class="d-block h5 mb-2"#}
{#                                   href="{% url 'catalog:single_apartment' apart.id %}">{{ apart.title }}</a>#}
{#                                <p>#}
{#                                    <i class="fa fa-map-marker-alt text-primary me-2"></i>#}
{#                                    {{ apart.address }}#}
{#                                </p>#}
{#                            </div>#}
{#                            <div class="d-flex border-top">#}
{#                                <small class="flex-fill text-center border-end py-2"><i#}
{#                                        class="fa fa-ruler-combined text-primary me-2"></i>#}
{#                                    Площадь: {{ apart.sqft_living }} м2#}
{#                                </small>#}
{#                                <small class="flex-fill text-center border-end py-2"><i#}
{#                                        class="fa fa-bed text-primary me-2"></i>#}
{#                                    Комнаты: {{ apart.bedrooms }}#}
{#                                </small>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{##}
{#                {% endfor %}#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
<!-- Property List End -->

templates/call_to_action.html
{% load static %}

<!-- Call to Action Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="bg-light rounded p-3">
            <div class="bg-white rounded p-4" style="border: 1px dashed rgba(0, 185, 142, .3)">
                <div class="row g-5 align-items-center">
                    <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                        <img class="img-fluid rounded w-100" src="{% static 'img/call-to-action.jpg' %}" alt="">
                    </div>
                    <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                        <div class="mb-4">
                            <h1 class="mb-3">Свяжитесь с Нашим Сертифицированным Агенством</h1>
                            <p>Свяжитесь с нами любым удобным способом. Например, позвоните или оставьте свой номер
                                телефона — перезвоним в течение 5 минут. Адрес и телефон указаны на странице
                                контактов.</p>
                        </div>
                        <a href="#" class="btn btn-primary py-3 px-4 me-2"><i class="fa fa-phone-alt me-2"></i>Контакты</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Call to Action End -->

templates/contact_base.html
<!-- Contact Start -->

<div class="col-12">
    <div class="row gy-4">
        <div class="col-md-6 col-lg-4 wow fadeIn" data-wow-delay="0.1s"
             style="visibility: visible; animation-delay: 0.1s; animation-name: fadeIn;">
            <div class="bg-light rounded p-3">
                <div class="d-flex align-items-center bg-white rounded p-3"
                     style="border: 1px dashed rgba(0, 185, 142, .3)">
                    <div class="icon me-3" style="width: 45px; height: 45px;">
                        <i class="fa fa-map-marker-alt text-primary"></i>
                    </div>
                    <span>КБР, г. Нальчик, ул. Пачева, д 36 офис 116</span>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4 wow fadeIn" data-wow-delay="0.3s"
             style="visibility: visible; animation-delay: 0.3s; animation-name: fadeIn;">
            <div class="bg-light rounded p-3">
                <div class="d-flex align-items-center bg-white rounded p-3"
                     style="border: 1px dashed rgba(0, 185, 142, .3)">
                    <div class="icon me-3" style="width: 45px; height: 45px;">
                        <i class="fa fa-envelope-open text-primary"></i>
                    </div>
                    <span>ramazanbaidaev@yandex.ru</span>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-4 wow fadeIn" data-wow-delay="0.5s"
             style="visibility: visible; animation-delay: 0.5s; animation-name: fadeIn;">
            <div class="bg-light rounded p-3">
                <div class="d-flex align-items-center bg-white rounded p-3"
                     style="border: 1px dashed rgba(0, 185, 142, .3)">
                    <div class="icon me-3" style="width: 45px; height: 45px;">
                        <i class="fa fa-phone-alt text-primary"></i>
                    </div>
                    <span>+7 903 493 96 90</span>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Contact End -->

templates/search.html
<!-- Search Start -->
<div class="container-fluid bg-light mb-5 wow fadeIn" data-wow-delay="0.1s" style="padding: 35px;">
    <div class="d-flex align-items-center bg-white rounded p-3"
         style="border: 1px dashed rgba(0, 185, 142, .3)">
        <div class="container">
            <div class="row g-2">
                <div class="col-md-10">
                    <div class="row g-2">
                        <div class="col-md-4">
                            <h6><i class="fa fa-bed text-primary me-2"></i>
                                Комнатность
                            </h6>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="exampleRadios"
                                       id="exampleRadios1"
                                       value="option1">
                                <label class="form-check-label text-dark fw-bold" for="exampleRadios1">
                                    1
                                </label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="exampleRadios"
                                       id="exampleRadios2"
                                       value="option2">
                                <label class="form-check-label text-dark fw-bold" for="exampleRadios2">
                                    2
                                </label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="exampleRadios"
                                       id="exampleRadios3"
                                       value="option2">
                                <label class="form-check-label text-dark fw-bold" for="exampleRadios3">
                                    3+
                                </label>
                            </div>
                        </div>
                        <div class="col-md-4 row py-4 py-md-0">
                            <h6><i class="fa fa-ruble-sign text-primary me-2"></i>
                                Стоимость</h6>
                            <div class="col pe-1">
                                <input type="text" class="form-control rounded-0 rounded-start" id="cc-expiration"
                                       placeholder="От"
                                       required="">
                            </div>

                            <div class="col ps-0">
                                <input type="text" class="form-control rounded-0 rounded-end" id="cc-cvv"
                                       placeholder="До" required="">
                            </div>
                        </div>
                        <div class="col-md-4 row">
                            <h6><i class="fa fa-ruler-combined text-primary me-2"></i>
                                Площадь, м2
                            </h6>
                            <div class="col pe-1">
                                <input type="text" class="form-control rounded-0 rounded-start" id="cc-expiration"
                                       placeholder="От" required="">
                            </div>

                            <div class="col ps-0">
                                <input type="text" class="form-control rounded-0 rounded-end" id="cc-cvv"
                                       placeholder="До" required="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <a class="btn btn-dark border-0 w-100 py-3" href="{% url 'catalog:apartments_list' %}">Поиск</a>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Search End -->

templates/testimonial.html
{% load static %}

<!-- Testimonial Start -->
<div class="container-xxl py-5 mt-5">
    <div class="container">
        <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">
            <h1 class="mb-3">Что о нас говорят?</h1>
            <p>96% клиентов довольны нашими услугами. С компанией сотрудничают эксперты в сфере
                недвижимости, которые непрерывно, вместе с нами, проходят обучение для предоставления
                качественных услуг. А после сделки - клиенты оценивают их работу.</p>
        </div>
        <div class="owl-carousel testimonial-carousel wow fadeInUp" data-wow-delay="0.1s">
            <div class="testimonial-item bg-light rounded p-3">
                <div class="bg-white border rounded p-4">
                    <p>Спасибо за помощь в приобретении квартиры и квалифицированное сопровождение сделки.</p>
                    <div class="d-flex align-items-center">
                        <img class="img-fluid flex-shrink-0 rounded" src="{% static 'img/client_img.svg' %}"
                             style="width: 45px; height: 45px;" alt="">
                        <div class="ps-3">
                            <h6 class="fw-bold mb-1">Татьяна</h6>
                            <small>Клиент</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="testimonial-item bg-light rounded p-3">
                <div class="bg-white border rounded p-4">
                    <p>Хочу выразить благодарность за грамотное сопровождение сделки, за четкость
                        и понимание поставленных целей. За выбором объекта обратилась к этим специалистам и уже на
                        следующий день сделка состоялась</p>
                    <div class="d-flex align-items-center">
                        <img class="img-fluid flex-shrink-0 rounded" src="{% static 'img/client_img.svg' %}"
                             style="width: 45px; height: 45px;" alt="">
                        <div class="ps-3">
                            <h6 class="fw-bold mb-1">Алена</h6>
                            <small>Специалист по недвижимости</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="testimonial-item bg-light rounded p-3">
                <div class="bg-white border rounded p-4">
                    <p>Если вы ищете надежное агентство недвижимости, то это отличный выбор! Рекомендую
                        их всем, кто ценит качество и профессионализм в работе.</p>
                    <div class="d-flex align-items-center">
                        <img class="img-fluid flex-shrink-0 rounded" src="{% static 'img/client_img.svg' %}"
                             style="width: 45px; height: 45px;" alt="">
                        <div class="ps-3">
                            <h6 class="fw-bold mb-1">Алим</h6>
                            <small>Клиент</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Testimonial End -->